# Generated by Django 2.0 on 2021-05-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_specialist',
            field=models.BooleanField(default=False, verbose_name='¿Es un especialista medico?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist',
            field=models.CharField(default='', max_length=120, verbose_name='Especialidad en'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_id',
            field=models.CharField(default='', max_length=25, verbose_name='Cedula profesional'),
        ),
    ]
